version: "3.3"

services:
#    mariadb-slave:
#        image: yidigun/mariadb-replication:10.7
#        restart: unless-stopped
#        container_name: jacq_prc_slave
#        hostname: herbarium2.natur.cuni.cz
#        ports:
#            - "3306:3306"
#        environment:
#            - TZ=Europe/Vienna
#            - LANG=de_AT.UTF-8
#            - REPL_MODE=slave
#            - REPL_SERVER_ID=10
#            - REPL_USERNAME=repl
#            - REPL_PASSWORD="something"
#            - REPL_MASTER_HOST=mariadb-master.jacq.com
#            - REPL_MASTER_PORT=3306
#        volumes:
#            - ./data/slave_jacq/data:/var/lib/mysql
#            - ./data/slave_jacq/log:/var/log/mysql
#            - ./data/slave_jacq/run:/run/mysqld

    phpmyadmin:
        image: phpmyadmin
        container_name: jacq_prc_myadmin
        ports:
            - 8080:80
        depends_on:
#            - mariadb-slave
            - mariadb-viewer
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=10M
            - MAX_EXECUTION_TIME=6000

    #    proxy:

    cantaloupe:
        build:
            context: ./_containers
            dockerfile: Dockerfile_cantaloupe
        container_name: jacq_prc_cantaloupe
        ports:
            - 8182:8182
        depends_on:
            - minio
        environment:
            HTTP_HTTP2_ENABLED: "true"
            HTTPS_HTTP2_ENABLED: "true"
            ENDPOINT_IIIF_CONTENT_DISPOSITION: none
            SOURCE_STATIC: S3Source
            S3SOURCE_ENDPOINT: http://minio:9000
            S3SOURCE_ACCESS_KEY_ID: minio
            S3SOURCE_SECRET_KEY: password
            S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME: prc
            PROCESSOR_SELECTION_STRATEGY: ManualSelectionStrategy
            PROCESSOR_MANUAL_SELECTIONSTRATEGY_JP2: OpenJpegProcessor
            CACHE_SERVER_DERIVATIVE_ENABLED: "true"
            CACHE_SERVER_DERIVATIVE: S3Cache
            CACHE_SERVIER_DERIVATIVE_TTL_SECONDS: 0
            CACHE_SERVER_PURGE_MISSING: "true"
            CACHE_SERVER_WORKER_ENABLED: "true"
            S3CACHE_ENDPOINT: http://minio:9000
            S3CACHE_ACCESS_KEY_ID: minio
            S3CACHE_SECRET_KEY: password
            S3CACHE_BUCKET_NAME: images
            S3CACHE_OBJECT_KEY_PREFIX: cache
            LOG_APPLICATION_LEVEL: warn
            LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"
    #            SOURCE_STATIC: FilesystemSource
    #            FILESYSTEMSOURCE_BASICLOOKUPSTRATEGY_PATH_PREFIX: "/imageroot/"
    #        volumes:
    #            - ./data/cantaloupe/:/imageroot

    minio:
        image: minio/minio
        container_name: jacq_prc_minio
        command: [ "server", "--console-address", ":9001", "/data" ]
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: password
        volumes:
            - minio_storage:/data

    viewer:
        image: dockette/web:php-83
        container_name: jacq_prc_viewer
        depends_on:
            - mariadb-viewer
        environment:
            NETTE_ENV: "development"
        ports:
            - 7080:80
        volumes:
            - ./viewer/htdocs:/srv/

    mariadb-viewer:
        image: mariadb:11
        container_name: jacq_prc_db_viewer
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: viewer
            MARIADB_DATABASE: viewer
            MARIADB_PASSWORD: viewer
        volumes:
            - mysql_viewer_storage:/var/lib/mysql

volumes:
    minio_storage: { }
    mysql_viewer_storage: { }
