services:
    proxy:
        image: steveltn/https-portal
        ports:
            - '80:80'
            - '443:443'
        restart: unless-stopped
        container_name: jacq-proxy
        links:
            - cantaloupe
            - curator
        environment:
            DOMAINS: 'herbarium2.natur.cuni.cz -> http://cantaloupe:8182'
            STAGE: 'local' # 'local' | 'production'
        volumes:
            - proxy_storage:/var/lib/https-portal
            - ./containers/proxy/herbarium2.natur.cuni.cz.ssl.conf.erb:/var/lib/nginx-conf/herbarium2.natur.cuni.cz.ssl.conf.erb:ro

    cantaloupe:
        build:
            context: containers
            dockerfile: Dockerfile_cantaloupe
        restart: unless-stopped
        container_name: jacq-cantaloupe
        ports:
            - 8182:8182
        depends_on:
            - minio
        environment:
            HTTP_HTTP2_ENABLED: "true"
            HTTPS_HTTP2_ENABLED: "true"
            ENDPOINT_IIIF_CONTENT_DISPOSITION: none
            ENDPOINT_ADMIN_ENABLED: "false"
            SOURCE_STATIC: S3Source
            S3SOURCE_ENDPOINT: http://minio:9000
            S3SOURCE_ACCESS_KEY_ID: ${S3_USER}
            S3SOURCE_SECRET_KEY: ${S3_PASSWD}
            S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME: prc
            PROCESSOR_SELECTION_STRATEGY: ManualSelectionStrategy
            PROCESSOR_MANUAL_SELECTIONSTRATEGY_JP2: OpenJpegProcessor
            CACHE_SERVER_DERIVATIVE_ENABLED: "true"
            CACHE_SERVER_DERIVATIVE: S3Cache
            CACHE_SERVIER_DERIVATIVE_TTL_SECONDS: 0
            CACHE_SERVER_PURGE_MISSING: "true"
            CACHE_SERVER_WORKER_ENABLED: "true"
            S3CACHE_ENDPOINT: http://minio:9000
            S3CACHE_ACCESS_KEY_ID: ${S3_USER}
            S3CACHE_SECRET_KEY: ${S3_PASSWD}
            S3CACHE_BUCKET_NAME: images
            S3CACHE_OBJECT_KEY_PREFIX: cache
            LOG_APPLICATION_LEVEL: warn
            LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "false"

    curator:
        image: dockette/web:php-83
        container_name: jacq-curator
        restart: unless-stopped
        depends_on:
            - curator-db
        environment:
            NETTE_ENV: "development"
        volumes:
            - ./containers/curator/htdocs:/srv/

    curator-db:
        image: mariadb:11
        container_name: jacq-curator-db
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: ${CURATOR_ROOT_PASSWORD}
            MARIADB_USER: curator
            MARIADB_DATABASE: curator
            MARIADB_PASSWORD: ${CURATOR_PASSWORD}
        volumes:
            - curator_db_storage:/var/lib/mysql

    minio:
        image: minio/minio
        container_name: jacq_minio
        restart: unless-stopped
        command: [ "server", "--console-address", ":9001", "/data" ]
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            - MINIO_ROOT_USER=${S3_USER}
            - MINIO_ROOT_PASSWORD=${S3_PASSWD}
        volumes:
            - minio_storage:/data

#    mariadb-slave:
#        image: yidigun/mariadb-replication:10.7
#        restart: unless-stopped
#        container_name: jacq-prc-slave
#        hostname: herbarium2.natur.cuni.cz
#        ports:
#            - "3306:3306"
#        environment:
#            - TZ=Europe/Vienna
#            - LANG=de_AT.UTF-8
#            - REPL_MODE=slave
#            - REPL_SERVER_ID=10
#            - REPL_USERNAME=${xx}
#            - REPL_PASSWORD=${xx}
#            - REPL_MASTER_HOST=mariadb-master.jacq.com
#            - REPL_MASTER_PORT=3306
#        volumes:
#            - ./data/slave_jacq/data:/var/lib/mysql
#            - ./data/slave_jacq/log:/var/log/mysql
#            - ./data/slave_jacq/run:/run/mysqld
#    phpmyadmin:
#        image: phpmyadmin
#        container_name: jacq_prc_myadmin
#        ports:
#            - 8080:80
#        depends_on:
##            - mariadb-slave
#        environment:
#            - PMA_ARBITRARY=1
#            - UPLOAD_LIMIT=10M
#            - MAX_EXECUTION_TIME=6000

volumes:
    minio_storage:
    proxy_storage:
    curator_db_storage:
