version: "3.3"

services:
#    mariadb-slave:
#        image: yidigun/mariadb-replication:10.7
#        restart: unless-stopped
#        container_name: jacq_prc_slave
#        hostname: herbarium2.natur.cuni.cz
##        ports: #only for development
##            - "3306:3306"
#        environment:
#            - TZ=Europe/Vienna
#            - LANG=de_AT.UTF-8
#            - REPL_MODE=slave
#            - REPL_SERVER_ID=10
#            - REPL_USERNAME=repl
#            - REPL_PASSWORD="something"
#            - REPL_MASTER_HOST=mariadb-master.jacq.com
#            - REPL_MASTER_PORT=3306
#        volumes:
#            - ./data/mariadb/data:/var/lib/mysql
#            - ./data/mariadb/log:/var/log/mysql
#            - ./data/mariadb/run:/run/mysqld
#
#    phpmyadmin:
#        image: phpmyadmin
#        container_name: jacq_prc_admin
##        ports:         #only for development
##          - 8080:80
#        depends_on:
#          - mariadb-slave
#        environment:
#          - PMA_ARBITRARY=1
#          - PMA_HOST=mariadb-slave
#          - UPLOAD_LIMIT=100M
#          - MAX_EXECUTION_TIME=6000

    cantaloupe:
        build:
            context: ./_containers
            dockerfile: Dockerfile_cantaloupe
        container_name: jacq_prc_iiif
        ports:
            - 8182:8182
        environment:
            HTTP_HTTP2_ENABLED: "true"
            HTTPS_HTTP2_ENABLED: "true"
            ENDPOINT_IIIF_CONTENT_DISPOSITION: none
            SOURCE_STATIC: FilesystemSource
            FILESYSTEMSOURCE_BASICLOOKUPSTRATEGY_PATH_PREFIX: "/imageroot/"
            LOG_APPLICATION_LEVEL: warn
            LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"
        volumes:
            - ./data/cantaloupe/:/imageroot

#    mirador:
