services:
    jacq-slave:
        image: mariadb:10
        restart: unless-stopped
        container_name: jacq-slave
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        volumes:
            - /storage/cesnet-du5/test/dbdump:/base
            - ./data:/var/lib/mysql
            - ./replica.cnf:/etc/mysql/conf.d/replica.cnf

    phpmyadmin:
        image: phpmyadmin
        container_name: jacq_prc_myadmin
        restart: unless-stopped
        ports:
            - 8080:80
        depends_on:
            - jacq-slave
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=10M
            - MAX_EXECUTION_TIME=6000
