services:
    proxy:
        image: steveltn/https-portal
        ports:
            - '80:80'
            - '443:443'
        restart: unless-stopped
        container_name: jacq-proxy
        links:
            - cantaloupe
            - curator
        environment:
            DOMAINS: 'herbarium2.natur.cuni.cz -> http://curator, herbarium-iiif.natur.cuni.cz -> http://cantaloupe:8182'
            STAGE: 'local' # 'local' | 'production'
        volumes:
            - proxy_storage:/var/lib/https-portal

    cantaloupe:
        image: ghcr.io/krkabol/jacq-cantaloupe:main
        restart: unless-stopped
        container_name: jacq-cantaloupe
        ports:
            - 8182:8182
        environment:
            HTTP_HTTP2_ENABLED: "true"
            HTTPS_HTTP2_ENABLED: "true"
            ENDPOINT_IIIF_CONTENT_DISPOSITION: none
            ENDPOINT_ADMIN_ENABLED: "false"
            SOURCE_STATIC: S3Source
            S3SOURCE_ENDPOINT: ${S3_ENDPOINT}
            S3SOURCE_ACCESS_KEY_ID: ${S3_USER}
            S3SOURCE_SECRET_KEY: ${S3_PASSWD}
            S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME: iiif
            PROCESSOR_SELECTION_STRATEGY: ManualSelectionStrategy
            PROCESSOR_MANUAL_SELECTIONSTRATEGY_JP2: OpenJpegProcessor
            CACHE_SERVER_DERIVATIVE_ENABLED: "true"
            CACHE_SERVER_DERIVATIVE: S3Cache
            CACHE_SERVIER_DERIVATIVE_TTL_SECONDS: 0
            CACHE_SERVER_PURGE_MISSING: "true"
            CACHE_SERVER_WORKER_ENABLED: "true"
            S3CACHE_ENDPOINT: https://s3.cl4.du.cesnet.cz
            S3CACHE_ACCESS_KEY_ID: ${S3_USER}
            S3CACHE_SECRET_KEY: ${S3_PASSWD}
            S3CACHE_BUCKET_NAME: images
            S3CACHE_OBJECT_KEY_PREFIX: cache
            LOG_APPLICATION_LEVEL: warn
            LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "false"

    curator:
        image: ghcr.io/krkabol/jacq-image-curator:main
        container_name: jacq-curator
        restart: unless-stopped
        depends_on:
            - curator-db
        environment:
            NETTE_ENV: "production"
        volumes:
            - ./local.neon:/srv/config/local.neon

    curator-db:
        image: mariadb:11
        container_name: jacq-curator-db
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: ${CURATOR_ROOT_PASSWORD}
            MARIADB_USER: curator
            MARIADB_DATABASE: curator
            MARIADB_PASSWORD: ${CURATOR_PASSWORD}
        volumes:
            - ./data/curator-db:/var/lib/mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin


#    mariadb-slave:
#        image: yidigun/mariadb-replication:10.7
#        restart: unless-stopped
#        container_name: jacq-prc-slave
#        hostname: herbarium2.natur.cuni.cz
#        ports:
#            - "3306:3306"
#        environment:
#            - TZ=Europe/Vienna
#            - LANG=de_AT.UTF-8
#            - REPL_MODE=slave
#            - REPL_SERVER_ID=10
#            - REPL_USERNAME=${xx}
#            - REPL_PASSWORD=${xx}
#            - REPL_MASTER_HOST=mariadb-master.jacq.com
#            - REPL_MASTER_PORT=3306
#        volumes:
#            - ./data/slave_jacq/data:/var/lib/mysql
#            - ./data/slave_jacq/log:/var/log/mysql
#            - ./data/slave_jacq/run:/run/mysqld

    phpmyadmin:
        image: phpmyadmin
        container_name: jacq_prc_myadmin
        restart: unless-stopped
        ports:
            - 8080:80
        depends_on:
#            - mariadb-slave
            - curator-db
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=10M
            - MAX_EXECUTION_TIME=6000

volumes:
    proxy_storage:
